version: '3'
services:
   db:
     image: postgres
     container_name: backend_postgres
     ports:
       - "5432:5432"
   web:
     build: .
     # command: python manage.py runserver 0.0.0.0:8000
     command: bash devutils/wait-for-postgres.sh
     container_name: backend_django
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db
